# Generated by Django 5.1 on 2024-09-07 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_projects_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='technology_used',
        ),
    ]
